<?php

namespace CodersLab\CodersBookBundle\Entity;

use Doctrine\ORM\EntityRepository;


/**
 * CLGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CLGroupRepository extends EntityRepository {
    
    public function searchAllGroups ($text) {
        
        $em = $this->getEntityManager();
        
        $query = $em->createQuery('SELECT clgroup FROM CodersBookBundle:CLGroup clgroup'
                . ' WHERE clgroup.name LIKE :text OR clgroup.lecturer LIKE :text')->setParameter('text', '%' . $text .'%');
        
        return $query->getResult();
    }
}
