<?php

namespace CodersLab\CodersBookBundle\Entity;

use Doctrine\ORM\EntityRepository;


/**
 * CLGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CLGroupRepository extends EntityRepository {
}
