<?php

namespace CodersLab\CodersBookBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PersonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonRepository extends EntityRepository {
    
    public function searchAllPeople ($text) {
        
        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT person FROM CodersBookBundle:Person  person'
                . ' WHERE person.name LIKE :text'
                . ' OR person.email LIKE :text'
                . ' OR person.phone LIKE :text'
                . ' OR person.github LIKE :text'
                . ' OR person.linkedin LIKE :text')->setParameter('text', '%' . $text .'%');
        
        return $query->getResult();
    }
}
